### ISSUE TITLE
How to build this project + basepath for influxdb

### ISSUE THREAD

**Issue by jcdauchy-moodys** [JorgeMaker/InfluxDBWorkBench#4]
How do you build this project, don't see any maven POM.xml

Moreover, would be really nice to be able to set the influxdb URL like this :

http://myKubernetes:8086/influxdb 

For people deploying influxdb in a kubernetes cluster.

Thanks

**Comment by JorgeMaker** [comment]
Hi, there is no POM.xml describing dependencies. There is a /lib folder containing all needed dependencies. Include them in your class path.
