### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Nemecsek** [JorgeMaker/InfluxDBWorkBench#5]
Hi. 
How to use it? I couldn't compile it...

**Comment by corndog2000** [comment]
You can download the compiled jar file from the "releases" section on github.

**Comment by bobstanl** [comment]
For the non-java-nese out there, on Linux, cd to the the directory with the .jar file. Then enter:
$ java -jar influxDBWorkBench.jar
Stumbled about getting weird errors till I found the "-jar" trick.

Nice software, allowed me to understand my influxdb data and even, by allowing me to edit the stock queries, helped me to understand the query language,
