### ISSUE TITLE
cant save connection

### ISSUE THREAD

**Issue by ghedolo** [JorgeMaker/InfluxDBWorkBench#6]
on mac 11.3.1 
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

connection setting panel 
fills fields
press save

i get 
"not possible to save connection"

**Comment by 3gyptian** [comment]
I had the same problem.  You just need to run the jar file out of a folder that you have read and write permissions and then it works like a charm!

**Comment by Pedroalbuquerque** [comment]
Hi there,

I just installed this app that already proved to be very useful. Great Job.

I am using MAC so was impossible to run the "original" version InfluxDB Studio.
I am facing however the same problem "not possible to save connection".

Is there anything I need to change after installing it ?
the  options to change folder permission does not seem valid in MAC (or am I wrong ?) .

thank for any help you can provide.
