### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by meteornv** [JorgeMaker/InfluxDBWorkBench#8]
Hi,

First, very cool project.

I can enter my credentials, test and ping my connection but i can't connect to my db server.

Nothing is happening when I click connect

**Comment by pakair** [comment]
Can you provide details ... 
I have a server (graf) with influxdb installed, I connect to graf:8086 and am able to query the db.

**Comment by meteornv** [comment]
Sorry, it was my mistake. I didn'tset up my db correctly.
